### PR TITLE
ATU96 , Extract xml generation and Blob uploads

### PR DESCRIPTION
**Pull request by SSYerawar**

### CODE REVIEW

**Comment by jcoales-nomensa** [comment]
The 4 classes in the functions project that are not actually functions, can we please move these into the services project. Also direct accessing the classes as static instances isn't ideal. I would much prefer a more SOLID approach using DI to inject the services with them being registered in program.cs in the usual way.

**Comment by lombardig-nomensa** [comment]
Depending on how long this process takes to run the approach implemented here may not be suitable. HttpTrigger functions have a max idle timeout of 230 seconds, so unless the trigger responds within this period the function will cause a timeout. If its a long running process then using Durable functions maybe a more suitable approach as these are specifically designed for longer running processes.

**Comment by jcoales-nomensa** [comment]
EiirDailyExtractHelpers ...this should not be done in the service layer ... the client should be setup in the startup.cs  and di used to bring it into the class ... i am already registering a searchindexclient in startup.cs

**Comment by jcoales-nomensa** [comment]
Not seeing any unit tests

**Comment by lombardig-nomensa** [comment]
The story mentions that there will be a need to trigger the process manually from an Admin screen should the extract fail. I can't see anywhere where we log the job and a status. It would be good to have a run log of jobs with a status, I think relying on the existence of the file to or a log entry in AI to alert a user that the job needs to be triggered be insufficient. Depends on how the feedback to the user is going to be handled.

**Comment by glinsolvency** [comment]
Closing PR without merge as ATU-96 is a spike

**Pull request closed without merging**
